"""
This is a setup.py script generated by py2applet

Usage:
    python build_app.py py2app
"""

from setuptools import setup

APP = ['mftp.py']
DATA_FILES = ['qt.conf']
OPTIONS = {
    'argv_emulation': True,
    'optimize' : 2,
    'plist': {'CFBundleShortVersionString':'0.1.0'},
    'includes': ['sip', 'PyQt4._qt', 'PyQt4.QtCore', 'PyQt4.QtGui', 'PyQt4.QtNetwork'],
    'excludes': ['PyQt4.QtDesigner', 'PyQt4.QtOpenGL', 'PyQt4.QtScript', 'PyQt4.QtSql', 'PyQt4.QtTest', 'PyQt4.QtWebKit', 'PyQt4.QtXml', 'PyQt4.phonon']          
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
